export const STAGES = [
  { id: 1, key: "new", name: "New Enquiry", color: "#87968e" },
  { id: 2, key: "interested", name: "Qualified", color: "#d8a34e" },
  { id: 3, key: "appointment", name: "Appointment Requested", color: "#4f7c72" },
  { id: 4, key: "confirmed", name: "Appointment Confirmed", color: "#2f6f62" },
  { id: 5, key: "visited", name: "Visited", color: "#6a8293" },
  { id: 6, key: "won", name: "Won", color: "#2f7d4e" },
];

const now = Date.now();
const isoAgo = (minutes) => new Date(now - minutes * 60_000).toISOString();

export const SAMPLE_LEADS = [
  { id: 101, name: "Amanda Lee", channel: "instagram", phone: "+60 12-*** 1188", language: "EN", treatment: "Pico Laser", temperature: "warm", stage: "interested", branch: "Kuala Lumpur", timing: "Weekday evening", value: 1200, owner: "Sarah", source: "Meta Ads", attention: false, unread: true, followUp: true, noReply: true, reschedule: false, cancelled: false, overdue: true, lastAt: isoAgo(8), summary: "Interested in Pico Laser for pigmentation and acne marks. Asked about pricing and downtime; no appointment time selected yet.", messages: [["user","Hi, I saw your Pico Laser ad. I have pigmentation and some acne marks. How much is it?",12],["assistant","Pico Laser starts from RM388 😊 It’s commonly used for pigmentation and uneven tone. Is pigmentation or acne marks your main concern?",11],["user","Mostly pigmentation. Is there downtime?",9],["assistant","Downtime depends on the settings and your skin condition. The clinic team can assess you first. Would you prefer KL or PJ if you decide to come in?",8],["user","KL is easier. I need to check my work schedule first.",8]] },
  { id: 102, name: "Nur Aisyah", channel: "whatsapp", phone: "+60 11-*** 2201", language: "BM", treatment: "Skin Booster", temperature: "hot", stage: "confirmed", branch: "Petaling Jaya", timing: "Saturday afternoon", value: 2200, owner: "Mira", source: "Meta Ads", attention: false, unread: false, followUp: false, noReply: false, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(24), summary: "Berminat dengan Skin Booster dan appointment Petaling Jaya pada Sabtu petang sudah disahkan oleh team klinik.", messages: [["user","Hai, skin booster harga berapa ya? Kulit saya agak kering dan kusam.",30],["assistant","Hai 😊 Skin Booster dalam demo ini bermula dari RM688. Nak saya bantu semak cawangan yang lebih senang untuk anda?",29],["user","PJ. Kalau Sabtu petang boleh datang?",25],["assistant","Boleh 😊 Saya dah catat Petaling Jaya dan Sabtu petang. Team klinik akan sahkan slot sebenar dengan anda.",24],["staff","Hi Aisyah, slot Sabtu 3:00 petang di PJ sudah confirmed. Jumpa nanti 😊",23]] },
  { id: 103, name: "林美玲 Mei Ling", channel: "instagram", phone: "@meiling.demo", language: "中文", treatment: "HIFU Skin Lifting", temperature: "cold", stage: "new", branch: "Kuala Lumpur", timing: "Not specified", value: 888, owner: "Unassigned", source: "Organic", attention: false, unread: true, followUp: false, noReply: false, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(61), summary: "询问 HIFU 下颚线紧致和价钱，目前只是初步了解，还没有预约意向。", messages: [["user","你好，请问HIFU主要是做什么的？我想改善下颚线。",65],["assistant","你好 😊 HIFU 一般用于紧致、提升和改善下颚线轮廓。这个示范诊所的 HIFU 从 RM888 起。",64],["user","先了解一下价钱，谢谢。",62],["assistant","当然可以 😊 有需要时再找我们就好。",61]] },
  { id: 104, name: "Farah Rahman", channel: "whatsapp", phone: "+60 17-*** 9041", language: "BM", treatment: "Pico Laser", temperature: "hot", stage: "appointment", branch: "Petaling Jaya", timing: "Needs another day", value: 1600, owner: "Mira", source: "Referral", attention: false, unread: false, followUp: false, noReply: false, reschedule: true, cancelled: false, overdue: false, lastAt: isoAgo(120), summary: "Mahukan Pico Laser di PJ dan meminta Ahad pagi, tetapi klinik tutup pada hari Ahad. Lead perlu pilih hari lain sebelum appointment boleh diteruskan.", messages: [["user","Kawan saya recommend Pico dekat sini. Saya ada pigmentation. Berapa satu session?",126],["assistant","Pico Laser bermula dari RM388 😊 Team biasanya akan tengok keadaan kulit dahulu.",125],["user","Saya nak book Ahad pagi dekat PJ boleh?",121],["assistant","Klinik tutup pada hari Ahad, jadi appointment Ahad tak dapat dibuat. Sabtu atau hari biasa lebih sesuai untuk anda?",120]] },
  { id: 105, name: "Michelle Tan", channel: "facebook", phone: "Messenger profile", language: "EN", treatment: "HIFU Skin Lifting", temperature: "warm", stage: "interested", branch: "Kuala Lumpur", timing: "Weekend", value: 1800, owner: "Sarah", source: "Meta Ads", attention: false, unread: true, followUp: true, noReply: false, reschedule: false, cancelled: false, overdue: true, lastAt: isoAgo(180), summary: "Interested in HIFU for lower-face tightening. Prefers KL and weekends but is comparing options before booking.", messages: [["user","Does HIFU help with lower face sagging?",186],["assistant","HIFU is commonly used for lifting and tightening areas such as the lower face and jawline. A consultation is best for deciding whether it fits your concern.",185],["user","Okay. I’m in KL and usually free on weekends. Let me compare first.",181],["assistant","Sure 😊 Take your time. I’ve noted KL and weekend as your preference.",180]] },
  { id: 106, name: "陈慧敏 Hui Min", channel: "whatsapp", phone: "+60 16-*** 6620", language: "中文", treatment: "Skin Booster", temperature: "hot", stage: "confirmed", branch: "Kuala Lumpur", timing: "Friday evening", value: 2400, owner: "Sarah", source: "Meta Ads", attention: false, unread: false, followUp: false, noReply: false, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(240), summary: "对 Skin Booster 有明确兴趣，吉隆坡星期五傍晚的预约已经由团队确认。", messages: [["user","Skin Booster 跟 Profhilo 有什么分别？我主要想改善干和细纹。",245],["assistant","两者都属于改善肤质和水润度的治疗方向，但具体选择需要看你的皮肤情况和目标。",244],["user","我想预约星期五晚上，KL。",241],["assistant","好的 😊 已记录吉隆坡和星期五傍晚。团队会再跟你确认实际可用时间。",240],["staff","您好，已经为您确认星期五 6:30pm 的 KL consultation 😊",239]] },
  { id: 107, name: "Sarah Lim", channel: "instagram", phone: "@sarah.demo", language: "EN", treatment: "Botulinum Toxin", temperature: "cold", stage: "new", branch: "Petaling Jaya", timing: "Not specified", value: 900, owner: "Unassigned", source: "Organic", attention: false, unread: false, followUp: false, noReply: false, reschedule: false, cancelled: true, overdue: false, lastAt: isoAgo(300), summary: "Asked about jaw-slimming injections and price. No appointment intent; sample lead later marked cancelled.", messages: [["user","Hi, do you do jaw slimming injections?",305],["assistant","Yes 😊 Botulinum Toxin can be used for selected muscle-related concerns such as jaw slimming. Pricing is quoted after consultation.",304],["user","Okay thanks, just checking first.",300]] },
  { id: 108, name: "Aina Sofea", channel: "whatsapp", phone: "+60 18-*** 7781", language: "BM", treatment: "HIFU Skin Lifting", temperature: "warm", stage: "interested", branch: "Kuala Lumpur", timing: "Weekday", value: 1500, owner: "Mira", source: "Meta Ads", attention: false, unread: false, followUp: true, noReply: true, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(1440), summary: "Berminat HIFU untuk double chin, sudah tanya harga dan cawangan KL. Belum pilih hari untuk appointment.", messages: [["user","HIFU boleh untuk double chin ke? Harga promo masih RM888?",1450],["assistant","Ya 😊 HIFU biasa digunakan untuk tightening dan jawline/double chin. Harga demo bermula RM888.",1449],["user","KL ada kan? Saya weekday lebih senang tapi belum tahu hari.",1440]] },
  { id: 109, name: "王佳恩 Jia En", channel: "facebook", phone: "Messenger profile", language: "中文", treatment: "Pico Laser", temperature: "warm", stage: "interested", branch: "Petaling Jaya", timing: "Weekday afternoon", value: 1300, owner: "Sarah", source: "Organic", attention: false, unread: false, followUp: true, noReply: false, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(1500), summary: "想改善色斑，已询问 Pico Laser 疗程和 PJ 分行，倾向平日下午但暂时未预约。", messages: [["user","请问PJ有Pico吗？我脸上有一些晒斑。",1510],["assistant","有的 😊 这个示范诊所的 Pico Laser 从 RM388 起，常用于色素、肤色不均等问题。",1509],["user","我通常平日下午有空，不过想先看看。",1500]] },
  { id: 110, name: "Daniel Wong", channel: "whatsapp", phone: "+60 12-*** 0191", language: "EN", treatment: "Botulinum Toxin", temperature: "hot", stage: "appointment", branch: "Kuala Lumpur", timing: "Tomorrow afternoon", value: 1800, owner: "Sarah", source: "Referral", attention: true, unread: true, followUp: false, noReply: false, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(1580), summary: "Wants an appointment for jaw-slimming consultation in KL tomorrow afternoon and requested a human consultant. Appointment requested; staff attention required before confirmation.", messages: [["user","I want to consult about jaw slimming. Can I come tomorrow afternoon in KL?",1590],["assistant","Sure 😊 I’ve noted KL and tomorrow afternoon. The team would confirm the actual available slot.",1588],["user","Can I speak with a human consultant before I decide?",1584],["assistant","Of course. I’ll flag this for a clinic team member to step in and help you directly.",1583],["staff","Hi Daniel, I’m Sarah from the clinic team. I can help with your questions before you decide.",1580]] },
  { id: 111, name: "Chloe Cheong", channel: "instagram", phone: "@chloe.demo", language: "EN", treatment: "Skin Booster", temperature: "hot", stage: "visited", branch: "Petaling Jaya", timing: "Completed visit", value: 2600, owner: "Mira", source: "Meta Ads", attention: false, unread: false, followUp: true, noReply: false, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(2880), summary: "Completed a clinic visit after enquiring about Skin Booster. Follow-up outcome is still open in the sample pipeline.", messages: [["user","I’m looking for something for dehydration and texture. Is Skin Booster suitable?",2900],["assistant","Skin Booster is commonly used to improve hydration, texture and overall skin quality. A consultation will help the team assess which option fits your goals.",2898],["user","Okay I can come PJ tomorrow around 3pm.",2890],["staff","Thanks Chloe, your consultation details are confirmed on our side. See you tomorrow.",2880]] },
  { id: 112, name: "Siti Hajar", channel: "whatsapp", phone: "+60 19-*** 3312", language: "BM", treatment: "HIFU Skin Lifting", temperature: "hot", stage: "won", branch: "Kuala Lumpur", timing: "Completed", value: 3200, owner: "Mira", source: "Meta Ads", attention: false, unread: false, followUp: false, noReply: false, reschedule: false, cancelled: false, overdue: false, lastAt: isoAgo(4320), summary: "Sample closed-won HIFU lead after consultation and clinic visit.", messages: [["user","Saya nak tahu HIFU untuk jawline. Kalau sesuai saya nak datang KL.",4350],["assistant","Boleh 😊 HIFU biasa digunakan untuk jawline dan tightening. Saya boleh catat KL untuk team follow up.",4349],["staff","Hi Siti, kami dah confirm konsultasi anda. Terima kasih!",4320]] },
];

export const ANALYTICS = {
  newLeads: 126, appointments: 34, visits: 25, won: 17,
  conversion: 13.5, appointmentRate: 27.0, showRate: 73.5, closeRate: 68.0,
  leadQuality: { hot: 19, warm: 47, cold: 60 },
  channels: { whatsapp: 86, instagram: 30, facebook: 10 },
  treatments: [["HIFU",38],["Pico Laser",31],["Skin Booster",22],["Botulinum Toxin",17],["Other",18]],
  aiHandled: 84, staffTakeover: 16, avgResponse: "4.2s",
};

export function portalMessages(lead) {
  return lead.messages.map(([role, text, minutes], index) => ({
    id: lead.id * 100 + index,
    role: role === "user" ? "user" : "assistant",
    source: role,
    text,
    created_at: isoAgo(minutes),
    delivery_status: role === "user" ? null : "read",
  }));
}
