const normalized = String(typeof __DEMO_INDUSTRY__ !== "undefined" ? __DEMO_INDUSTRY__ : "clinic")
  .trim()
  .toLowerCase();

const renovationAliases = new Set(["renovation", "home-renovation", "carpentry"]);

const clinicProfile = {
  key: "clinic",
  businessName: "Nova Demo Aesthetic Clinic",
  shortBusinessName: "Nova Demo Clinic",
  assistantName: "Avery",
  terms: {
    customer: "Patient",
    customerLower: "patient",
    business: "clinic",
    businessTitle: "Clinic",
    staff: "Clinic staff",
    service: "Treatment",
    servicePlural: "Treatments",
    location: "Branch",
    locationPlural: "Branches",
    timing: "Timing",
    appointment: "Appointment",
    appointmentPlural: "Appointments",
  },
  serviceAreas: ["Kuala Lumpur", "Petaling Jaya"],
  teamMembers: [
    { name: "Demo Admin", username: "demo", role: "Admin", scope: "All leads", status: "Active" },
    { name: "Sarah", username: "sarah.demo", role: "Sales", scope: "Assigned leads", status: "Active" },
    { name: "Mira", username: "mira.demo", role: "Sales", scope: "Assigned leads", status: "Active" },
  ],
  acquisitionPresets: {
    "hifu-facebook": { key: "hifu-facebook", label: "HIFU Facebook Ad", source: "Meta Ads", campaign: "HIFU Demo Campaign", treatment: "HIFU Skin Lifting", channel: "facebook" },
    "pico-instagram": { key: "pico-instagram", label: "Pico Instagram Ad", source: "Meta Ads", campaign: "Pico Demo Campaign", treatment: "Pico Laser", channel: "instagram" },
    "organic-whatsapp": { key: "organic-whatsapp", label: "Organic WhatsApp", source: "Organic", campaign: null, treatment: null, channel: "whatsapp" },
    referral: { key: "referral", label: "Referral", source: "Referral", campaign: null, treatment: null, channel: "whatsapp" },
  },
  settings: {
    intro: "Clinic configuration and AI receptionist preferences.",
    profileTab: "Clinic profile",
    profileTitle: "Clinic profile",
    profileCopy: "The live product uses these details when answering patient enquiries.",
    fields: { name: "Clinic name", assistant: "AI assistant name", hours: "Business hours", locations: "Branches" },
    values: { name: "Nova Demo Aesthetic Clinic", assistant: "Avery", hours: "Mon–Sat, 10:00 AM – 7:00 PM", locations: "Kuala Lumpur, Petaling Jaya" },
    aiTitle: "AI receptionist",
    aiCopy: "Control how the assistant speaks and when a conversation should move to staff.",
    aiRows: [
      ["Match customer language", "Reply in English, Bahasa Malaysia or Chinese when practical."],
      ["Human handoff", "Escalate clinical questions, complaints, complications and direct requests for staff."],
      ["Appointment intent detection", "Recognise booking intent and capture branch/timing preferences."],
      ["Price guardrails", "Only quote treatment prices configured for the clinic."],
    ],
    channelsCopy: "Production deployments connect directly to your clinic accounts.",
    promotion: { title: "HIFU Demo Special", copy: "HIFU from RM888 · complimentary consultation · shown only when HIFU is relevant." },
  },
  tools: {
    disconnectedCopy: "Demo settings are not connected to a real clinic.",
    followUpDefaults: {
      en: "Hi! Just checking in to see if you still need any help. Feel free to reply whenever you're ready 😊",
      ms: "Hai! Saya cuma ingin bertanya sama ada anda masih memerlukan bantuan. Balas sahaja apabila anda sudah bersedia 😊",
      zh: "嗨！想跟进一下，看看您是否还需要任何帮助。方便时回复我们就可以了 😊",
    },
    sampleLeadName: "Amanda Lee",
    sampleLeadService: "Pico Laser",
    sampleLeadArea: "Kuala Lumpur",
    quietCopy: "no reply after the clinic's last message",
    customerCheck: "Patient has not replied",
    chatPreviewTitle: "Patient chat preview",
    sampleCustomerMessage: "KL is easier. I need to check my work schedule first.",
    sampleAssistantMessage: "No problem 😊 Take your time. Let me know if you'd like help choosing a slot.",
    checkingCopy: "Checking for a new patient reply…",
    previewEligibility: "Before it sends, the production system checks that the patient has not already replied and that the conversation is still eligible.",
    scoringTitle: "Prioritise the enquiries most likely to book",
    hotCopy: "Strong booking intent, appointment timing, or a clear request to proceed.",
    warmCopy: "Active treatment or pricing interest but no firm booking intent yet.",
    comingNext: ["Appointment reminders", "Promotional campaigns", "Review requests"],
  },
  analytics: {
    locationOptions: [["all", "All branches"], ["Kuala Lumpur", "Kuala Lumpur"], ["Petaling Jaya", "Petaling Jaya"]],
    campaignOptions: [["all", "All campaigns"], ["Demo", "Demo Clinic Campaign"]],
    serviceOptions: [["all", "All treatments"], ["HIFU Skin Lifting", "HIFU"], ["Pico Laser", "Pico Laser"], ["Skin Booster", "Skin Booster"], ["Botulinum Toxin", "Botulinum Toxin"]],
    ownerOptions: [["all", "All owners"], ["Mira", "Mira"], ["Sarah", "Sarah"], ["Unassigned", "Unassigned"]],
    funnel: ["New Leads", "Appointments", "Clinic Visits", "Won"],
    metrics: ["Appointments", "Clinic Visits"],
    rates: [["Appointment rate", "Lead → appointment"], ["Show rate", "Appointment → visit"], ["Close rate", "Visit → won"]],
    breakdownTabs: ["Source", "Campaign", "Treatment", "Branch", "Channel", "Owner"],
    breakdownCopy: "Compare which sources, campaigns, treatments, branches, channels and owners drive results.",
    systemName: "AI receptionist",
  },
};

const renovationProfile = {
  key: "renovation",
  businessName: "Oakline Demo Renovation & Carpentry",
  shortBusinessName: "Oakline Demo Renovation",
  assistantName: "Aiden",
  terms: {
    customer: "Customer",
    customerLower: "customer",
    business: "renovation company",
    businessTitle: "Renovation Company",
    staff: "Renovation staff",
    service: "Project",
    servicePlural: "Projects",
    location: "Area",
    locationPlural: "Service areas",
    timing: "Timeline",
    appointment: "Site measurement",
    appointmentPlural: "Site measurements",
  },
  serviceAreas: ["Kuala Lumpur", "Petaling Jaya / Subang / Shah Alam", "Cheras / Kajang / Puchong"],
  teamMembers: [
    { name: "Demo Admin", username: "demo", role: "Admin", scope: "All leads", status: "Active" },
    { name: "Amir", username: "amir.demo", role: "Sales", scope: "Assigned leads", status: "Active" },
    { name: "Mei", username: "mei.demo", role: "Designer", scope: "Assigned leads", status: "Active" },
    { name: "Aina", username: "aina.demo", role: "Project Sales", scope: "Assigned leads", status: "Active" },
  ],
  acquisitionPresets: {
    "hifu-facebook": { key: "hifu-facebook", label: "Kitchen Cabinets Facebook Ad", source: "Meta Ads", campaign: "Kitchen Cabinets Demo Campaign", treatment: "Kitchen Cabinets", channel: "facebook" },
    "pico-instagram": { key: "pico-instagram", label: "Wardrobe Instagram Ad", source: "Meta Ads", campaign: "Built-in Wardrobe Demo Campaign", treatment: "Built-in Wardrobes", channel: "instagram" },
    "organic-whatsapp": { key: "organic-whatsapp", label: "Organic WhatsApp", source: "Organic", campaign: null, treatment: null, channel: "whatsapp" },
    referral: { key: "referral", label: "Referral", source: "Referral", campaign: null, treatment: null, channel: "whatsapp" },
  },
  settings: {
    intro: "Renovation business configuration and AI sales-assistant preferences.",
    profileTab: "Business profile",
    profileTitle: "Renovation business profile",
    profileCopy: "The live product uses these details when answering renovation and carpentry enquiries.",
    fields: { name: "Business name", assistant: "AI assistant name", hours: "Business hours", locations: "Service areas" },
    values: { name: "Oakline Demo Renovation & Carpentry", assistant: "Aiden", hours: "Mon–Sat, 9:00 AM – 6:00 PM", locations: "Kuala Lumpur; PJ / Subang / Shah Alam; Cheras / Kajang / Puchong" },
    aiTitle: "AI sales assistant",
    aiCopy: "Control how the assistant qualifies renovation enquiries and when a conversation should move to your team.",
    aiRows: [
      ["Match customer language", "Reply naturally in English, Bahasa Malaysia or Chinese based on the customer's language."],
      ["Human handoff", "Escalate site-specific technical questions, complaints and direct requests for a designer or salesperson."],
      ["Quotation & measurement intent", "Detect proper-quotation and site-measurement requests while keeping them as separate lead signals."],
      ["Price guardrails", "Use configured starting guides only and never invent a final renovation quotation from chat."],
    ],
    channelsCopy: "Production deployments connect directly to the renovation company's WhatsApp, Instagram and Facebook accounts.",
    promotion: null,
  },
  tools: {
    disconnectedCopy: "Demo settings are not connected to a real renovation company.",
    followUpDefaults: {
      en: "Hi! Just checking in — let me know if you still need help with your renovation quotation or carpentry planning 😊",
      ms: "Hai! Nak follow up sekejap — beritahu saya kalau masih perlukan bantuan untuk quotation renovation atau carpentry ya 😊",
      zh: "嗨！想跟进一下，如果你还需要装修报价或木工规划方面的帮助，随时告诉我 😊",
    },
    sampleLeadName: "Nur Izzati",
    sampleLeadService: "Built-in Wardrobes",
    sampleLeadArea: "Petaling Jaya / Subang / Shah Alam",
    quietCopy: "no reply after the renovation team's last message",
    customerCheck: "Customer has not replied",
    chatPreviewTitle: "Customer chat preview",
    sampleCustomerMessage: "Budget around RM7k. I need to compare first before deciding.",
    sampleAssistantMessage: "No problem. The final wardrobe quote depends on size, door style and internal layout. I can follow up later if you still need help.",
    checkingCopy: "Checking for a new customer reply…",
    previewEligibility: "Before it sends, the production system checks that the customer has not already replied and that the project enquiry is still eligible.",
    scoringTitle: "Prioritise the renovation enquiries most likely to proceed",
    hotCopy: "Strong quotation/site-measurement intent, or a qualified customer asking to speak with the team.",
    warmCopy: "Active carpentry, pricing or planning interest without a firm quotation/site-measurement request yet.",
    comingNext: ["Site-measurement reminders", "Quotation follow-ups", "Review requests"],
  },
  analytics: {
    locationOptions: [["all", "All areas"], ["Kuala Lumpur", "Kuala Lumpur"], ["Petaling Jaya / Subang / Shah Alam", "PJ / Subang / Shah Alam"], ["Cheras / Kajang / Puchong", "Cheras / Kajang / Puchong"]],
    campaignOptions: [["all", "All campaigns"], ["Demo", "Demo Renovation Campaign"]],
    serviceOptions: [["all", "All projects"], ["Kitchen Cabinets", "Kitchen Cabinets"], ["Built-in Wardrobes", "Built-in Wardrobes"], ["TV Console & Living Room Carpentry", "Living Room Carpentry"], ["Shoe Cabinet & Entrance Storage", "Shoe / Entrance Storage"], ["Study, Display & Storage Cabinets", "Study / Display / Storage"], ["Full-Home Custom Carpentry", "Full-Home Carpentry"]],
    ownerOptions: [["all", "All owners"], ["Amir", "Amir"], ["Mei", "Mei"], ["Aina", "Aina"], ["Unassigned", "Unassigned"]],
    funnel: ["New Leads", "Site Measurements", "Quotations / Design", "Won"],
    metrics: ["Site Measurements", "Quotations / Design"],
    rates: [["Measurement rate", "Lead → measurement"], ["Quotation rate", "Measurement → quotation"], ["Close rate", "Quotation → won"]],
    breakdownTabs: ["Source", "Campaign", "Project", "Area", "Channel", "Owner"],
    breakdownCopy: "Compare which sources, campaigns, projects, service areas, channels and owners drive renovation opportunities.",
    systemName: "AI sales assistant",
  },
};

export const industryProfile = renovationAliases.has(normalized) ? renovationProfile : clinicProfile;
export const demoIndustry = industryProfile.key;
export const isRenovationDemo = industryProfile.key === "renovation";
export const demoTerms = industryProfile.terms;
