import { useMemo, useState } from "react";
import { ANALYTICS } from "../demoData";

const PRESETS=[["7","Last 7 days"],["30","Last 30 days"],["90","Last 90 days"],["custom","Custom range"]];
export default function Analytics(){
  const [preset,setPreset]=useState("30"); const [branch,setBranch]=useState("all"); const [channel,setChannel]=useState("all"); const [more,setMore]=useState(false); const [tab,setTab]=useState("Source");
  const a=ANALYTICS;
  const funnel=useMemo(()=>[["New Leads",a.newLeads,100],["Appointments",a.appointments,a.appointmentRate],["Clinic Visits",a.visits,(a.visits/a.newLeads)*100],["Won",a.won,a.conversion]],[a]);
  return <div className="h-full overflow-y-auto overscroll-contain bg-[var(--color-bg)]">
    <header className="border-b border-[var(--color-border)] bg-[var(--color-surface)] px-3.5 py-4 sm:px-5 sm:py-5 lg:px-7">
      <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2.5"><h1 className="font-display text-xl font-bold">Analytics</h1><span className="rounded-full bg-[var(--color-primary-light)] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[var(--color-primary)]">Sales</span><span className="rounded-full border border-[var(--color-border)] bg-[var(--color-bg)] px-2.5 py-1 text-[10px] font-semibold text-[var(--color-text-muted)]">Sample demo data</span></div><p className="mt-1 max-w-3xl text-xs leading-relaxed text-[var(--color-text-muted)] sm:text-sm">Track lead quality, conversion, response speed and sales outcomes. <span className="hidden sm:inline">See where enquiries drop off and which channels turn into clinic visits and wins.</span></p></div><button className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-[var(--color-border)] bg-white text-lg font-semibold text-[var(--color-text-muted)] shadow-sm hover:bg-[var(--color-bg)]">↻</button></div>
      <div className="mt-4 grid grid-cols-2 gap-2.5 sm:flex sm:flex-wrap sm:items-end"><Filter label="Date range" value={preset} onChange={setPreset} options={PRESETS}/><Filter label="Branch" value={branch} onChange={setBranch} options={[["all","All branches"],["Kuala Lumpur","Kuala Lumpur"],["Petaling Jaya","Petaling Jaya"]]}/><Filter label="Channel" value={channel} onChange={setChannel} options={[["all","All channels"],["whatsapp","WhatsApp"],["instagram","Instagram"],["facebook","Facebook"]]}/><button onClick={()=>setMore(!more)} className={`h-11 rounded-xl border px-3.5 text-xs font-semibold ${more?"border-[var(--color-primary)] bg-[var(--color-primary-light)] text-[var(--color-primary)]":"border-[var(--color-border)] bg-white text-[var(--color-text-muted)]"}`}>Filters</button><button className="h-11 rounded-xl bg-[var(--color-primary)] px-4 text-xs font-bold text-white shadow-sm">Apply</button></div>
      {more&&<div className="mt-3 grid grid-cols-2 gap-2.5 rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg)] p-3 sm:grid-cols-4"><Filter label="Source" value="all" options={[["all","All sources"],["Meta Ads","Meta Ads"],["Organic","Organic"],["Referral","Referral"]]}/><Filter label="Campaign" value="all" options={[["all","All campaigns"],["Demo","Demo Clinic Campaign"]]}/><Filter label="Treatment" value="all" options={[["all","All treatments"],["HIFU","HIFU"],["Pico","Pico Laser"],["Skin","Skin Booster"]]}/><Filter label="Owner" value="all" options={[["all","All owners"],["Mira","Mira"],["Sarah","Sarah"]]}/></div>}
    </header>
    <main className="space-y-4 px-3.5 py-4 sm:space-y-5 sm:px-5 sm:py-5 lg:px-7 lg:py-6">
      <section className="grid grid-cols-2 gap-2.5 sm:gap-3 xl:grid-cols-5"><Metric label="New Leads" value={a.newLeads} delta="+12.5%" detail="Lead journeys started in this period"/><Metric label="Appointments" value={a.appointments} delta="+8.2%" detail="First appointment stage entered"/><Metric label="Clinic Visits" value={a.visits} delta="+6.4%" detail="First visit stage entered"/><Metric label="Won" value={a.won} delta="+13.3%" detail="Estimated value RM 42.8K"/><Metric className="col-span-2 xl:col-span-1" label="Cohort Conversion" value={`${a.conversion.toFixed(1)}%`} delta="+1.8 pp" detail="Leads started → Won"/></section>
      <section className="grid grid-cols-3 overflow-hidden rounded-2xl border border-[var(--color-border)] bg-white shadow-sm"><Rate label="Appointment rate" value={`${a.appointmentRate.toFixed(1)}%`} detail="Lead → appointment"/><Rate label="Show rate" value={`${a.showRate.toFixed(1)}%`} detail="Appointment → visit"/><Rate label="Close rate" value={`${a.closeRate.toFixed(1)}%`} detail="Visit → won"/></section>
      <section className="grid gap-4 sm:gap-5 xl:grid-cols-[0.85fr_1.15fr]"><Panel title="Conversion Funnel" subtitle="How the selected lead cohort progresses through the sales journey."><div className="space-y-4">{funnel.map(([name,count,pct],i)=><div key={name}><div className="mb-1.5 flex items-end justify-between"><div><strong className="text-xs">{name}</strong>{i>0&&<p className="text-[10px] text-[var(--color-text-muted)]">{pct.toFixed(1)}% of leads</p>}</div><b className="font-display text-lg">{count}</b></div><div className="h-2.5 overflow-hidden rounded-full bg-[var(--color-bg)]"><div className="h-full rounded-full bg-[var(--color-primary)]" style={{width:`${Math.max(8,pct)}%`}}/></div></div>)}</div></Panel><Panel title="Activity Over Time" subtitle="Daily activity based on when each event actually happened."><Trend/></Panel></section>
      <section className="grid gap-4 sm:gap-5 xl:grid-cols-2"><Panel title="Lead Quality" subtitle="Current Hot / Warm / Cold status for leads that started in this period."><Quality a={a}/></Panel><Panel title="Response Performance" subtitle="How quickly customer enquiries receive a reply."><div className="grid grid-cols-2 gap-3"><Mini label="Average AI response" value={a.avgResponse}/><Mini label="Handled by AI" value={`${a.aiHandled}%`}/><Mini label="Staff takeover" value={`${a.staffTakeover}%`}/><Mini label="Within 10 seconds" value="96%"/></div></Panel></section>
      <Panel title="Performance Breakdown" subtitle="Compare which sources, campaigns, treatments, branches, channels and owners drive results."><div className="flex gap-1.5 overflow-x-auto pb-3">{["Source","Campaign","Treatment","Branch","Channel","Owner"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-3 py-1.5 text-[10px] font-semibold ${tab===x?"bg-[var(--color-primary)] text-white":"border border-[var(--color-border)] bg-white text-[var(--color-text-muted)]"}`}>{x}</button>)}</div><Breakdown tab={tab}/></Panel>
      <section className="grid gap-4 sm:gap-5 xl:grid-cols-3"><Panel title="Follow-up Performance" subtitle="How follow-up activity contributes to outcomes."><StatRows rows={[["Follow-ups sent","41"],["Re-engaged leads","18"],["Converted after follow-up","7"]]}/></Panel><Panel title="Lost Reasons" subtitle="Why opportunities did not progress."><StatRows rows={[["No response","12"],["Price / budget","8"],["Not ready yet","6"],["Other","4"]]}/></Panel><Panel title="System Health" subtitle="Demo automation status."><StatRows rows={[["AI receptionist","Active"],["Lead temperature","Active"],["Automated follow-up","Active"],["Human handoff","Ready"]]}/></Panel></section>
    </main>
  </div>
}
function Filter({label,value,onChange=()=>{},options}){return <label className="min-w-0"><span className="mb-1 block text-[9px] font-bold uppercase tracking-wide text-[var(--color-text-muted)]">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full min-w-[9rem] rounded-xl border border-[var(--color-border)] bg-white px-3 text-xs font-medium outline-none focus:border-[var(--color-primary)]">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Metric({label,value,delta,detail,className=""}){return <div className={`rounded-2xl border border-[var(--color-border)] bg-white p-4 shadow-sm ${className}`}><p className="text-[9px] font-bold uppercase tracking-wide text-[var(--color-text-muted)]">{label}</p><div className="mt-2 flex items-end justify-between gap-2"><strong className="font-display text-2xl font-bold">{value}</strong><span className="text-[10px] font-semibold text-[var(--color-primary)]">{delta}</span></div><p className="mt-2 text-[10px] leading-4 text-[var(--color-text-muted)]">{detail}</p></div>}
function Rate({label,value,detail}){return <div className="border-r border-[var(--color-border)] p-3 text-center last:border-r-0 sm:p-4"><p className="text-[9px] font-bold uppercase tracking-wide text-[var(--color-text-muted)]">{label}</p><strong className="mt-1 block font-display text-lg font-bold sm:text-xl">{value}</strong><p className="mt-1 text-[9px] text-[var(--color-text-muted)]">{detail}</p></div>}
function Panel({title,subtitle,children}){return <section className="rounded-2xl border border-[var(--color-border)] bg-white p-4 shadow-sm sm:p-5"><h2 className="font-display text-sm font-bold sm:text-base">{title}</h2><p className="mt-1 text-[10px] leading-4 text-[var(--color-text-muted)] sm:text-xs">{subtitle}</p><div className="mt-5">{children}</div></section>}
function Trend(){const pts=[42,51,45,65,58,74,70,84,77,91,86,98];return <div className="overflow-x-auto"><svg viewBox="0 0 600 220" className="min-w-[520px] w-full" aria-label="Leads over time"><g stroke="#e6e5de" strokeWidth="1">{[40,80,120,160,200].map(y=><line key={y} x1="20" y1={y} x2="580" y2={y}/>)}</g><polyline fill="none" stroke="#2f6f62" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" points={pts.map((v,i)=>`${25+i*50},${200-v*1.55}`).join(" ")}/>{pts.map((v,i)=><circle key={i} cx={25+i*50} cy={200-v*1.55} r="4" fill="#fff" stroke="#2f6f62" strokeWidth="3"/>)}</svg></div>}
function Quality({a}){const total=a.leadQuality.hot+a.leadQuality.warm+a.leadQuality.cold;return <div className="space-y-4">{[["Hot",a.leadQuality.hot,"bg-[var(--color-danger)]"],["Warm",a.leadQuality.warm,"bg-[var(--color-accent)]"],["Cold",a.leadQuality.cold,"bg-slate-400"]].map(([l,v,c])=><div key={l}><div className="mb-1.5 flex justify-between text-xs"><span>{l}</span><strong>{v}</strong></div><div className="h-2.5 rounded-full bg-[var(--color-bg)]"><div className={`h-full rounded-full ${c}`} style={{width:`${v/total*100}%`}}/></div></div>)}</div>}
function Mini({label,value}){return <div className="rounded-xl bg-[var(--color-bg)] p-3"><p className="text-[9px] font-bold uppercase tracking-wide text-[var(--color-text-muted)]">{label}</p><strong className="mt-1 block font-display text-lg">{value}</strong></div>}
function Breakdown({tab}){const rows=tab==="Channel"?[["WhatsApp","68%","19 won"],["Instagram","24%","6 won"],["Facebook","8%","2 won"]]:tab==="Treatment"?[["HIFU","38 leads","7 won"],["Pico Laser","31 leads","4 won"],["Skin Booster","22 leads","4 won"],["Botulinum Toxin","17 leads","2 won"]]:[["Meta Ads","74 leads","12 won"],["Organic","31 leads","3 won"],["Referral","21 leads","2 won"]];return <div className="divide-y divide-[var(--color-border)]">{rows.map(r=><div key={r[0]} className="grid grid-cols-3 gap-2 py-3 text-xs"><strong>{r[0]}</strong><span className="text-[var(--color-text-muted)]">{r[1]}</span><span className="text-right font-semibold text-[var(--color-primary)]">{r[2]}</span></div>)}</div>}
function StatRows({rows}){return <div className="divide-y divide-[var(--color-border)]">{rows.map(([a,b])=><div key={a} className="flex justify-between gap-3 py-3 text-xs"><span className="text-[var(--color-text-muted)]">{a}</span><strong>{b}</strong></div>)}</div>}
