import { useMemo, useState } from "react";
import ContactAvatar from "../components/ContactAvatar";
import { SAMPLE_LEADS } from "../demoData";

export default function Contacts(){
 const [query,setQuery]=useState(""); const [selectedId,setSelectedId]=useState(null);
 const contacts=useMemo(()=>SAMPLE_LEADS.filter(l=>[l.name,l.phone,l.treatment,l.summary].join(" ").toLowerCase().includes(query.trim().toLowerCase())),[query]);
 const selected=SAMPLE_LEADS.find(l=>l.id===selectedId);
 return <div className="flex h-full min-w-0 bg-[var(--color-bg)]">
  <div className={`${selected?"hidden md:flex":"flex"} h-full w-full min-w-0 shrink-0 flex-col overflow-y-auto border-r border-[var(--color-border)] bg-white md:w-80`}><div className="sticky top-0 z-10 border-b border-[var(--color-border)] bg-white px-4 py-4 sm:px-5"><div className="flex items-center justify-between gap-2"><div><h1 className="font-display text-lg font-bold">Contacts</h1><p className="mt-0.5 text-xs text-[var(--color-text-muted)]">{contacts.length} contacts · sample demo data</p></div><button className="inline-flex shrink-0 items-center gap-1.5 rounded-lg bg-[var(--color-primary)] px-3 py-2 text-xs font-medium text-white">+ Add</button></div><input className="mt-3 w-full rounded-xl border border-[var(--color-border)] bg-white px-3.5 py-2.5 text-xs leading-relaxed outline-none focus:ring-2 focus:ring-[var(--color-primary)]" placeholder="Search by name, number or social ID…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{contacts.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`relative w-full border-b border-[var(--color-border)] px-4 py-3.5 text-left transition sm:px-5 ${c.id===selectedId?"bg-[var(--color-primary-light)]":c.attention?"bg-[var(--color-danger-light)]":"hover:bg-[var(--color-bg)]"}`}><div className="flex items-center gap-3"><ContactAvatar channel={c.channel}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><span className="truncate text-sm font-medium">{c.name}</span><span className="text-[10px] text-[var(--color-text-muted)]">{c.language}</span></div><p className="mt-0.5 truncate text-xs text-[var(--color-text-muted)]">{c.phone} · {c.treatment}</p></div></div></button>)}</div>
  <div className={`${selected?"block":"hidden md:block"} min-w-0 flex-1 overflow-y-auto`}>{selected?<Profile c={selected} back={()=>setSelectedId(null)}/>:<div className="flex h-full items-center justify-center px-6 text-center"><p className="text-sm text-[var(--color-text-muted)]">Select a contact to view their profile.</p></div>}</div>
 </div>
}
function Profile({c,back}){return <div className="mx-auto max-w-4xl px-4 py-5 sm:px-6 lg:px-8 lg:py-8"><button onClick={back} className="mb-4 rounded-lg px-2 py-1 text-xs font-semibold text-[var(--color-primary)] md:hidden">← Back to contacts</button><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><ContactAvatar channel={c.channel} size={64}/><div><h1 className="font-display text-2xl font-bold">{c.name}</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">{c.phone}</p><div className="mt-2 flex gap-2"><span className="rounded-full bg-[var(--color-primary-light)] px-2 py-1 text-[9px] font-semibold text-[var(--color-primary)]">{c.channel}</span><span className="rounded-full bg-[var(--color-accent-light)] px-2 py-1 text-[9px] font-semibold">{c.language}</span></div></div></div><button className="rounded-xl border border-[var(--color-border)] bg-white px-4 py-2 text-xs font-semibold">Edit contact</button></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-[var(--color-border)] bg-white p-5 shadow-sm"><h2 className="font-display text-sm font-bold">Contact details</h2><Facts rows={[["Treatment",c.treatment],["Branch",c.branch],["Timing",c.timing],["Source",c.source],["Owner",c.owner],["Language",c.language]]}/></section><section className="rounded-2xl border border-[var(--color-border)] bg-white p-5 shadow-sm"><h2 className="font-display text-sm font-bold">AI insights</h2><div className="mt-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${c.temperature==="hot"?"bg-[var(--color-danger-light)] text-[var(--color-danger)]":c.temperature==="warm"?"bg-[var(--color-accent-light)] text-[#8a641f]":"bg-slate-100 text-slate-600"}`}>{c.temperature}</span><p className="mt-4 text-sm leading-6">{c.summary}</p></div></section></div><section className="mt-4 rounded-2xl border border-[var(--color-border)] bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="font-display text-sm font-bold">Notes</h2><span className="text-[10px] text-[var(--color-text-muted)]">Demo workspace</span></div><textarea placeholder="Add an internal note…" rows="3" className="mt-4 w-full resize-none rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] p-3 text-sm outline-none focus:border-[var(--color-primary)]"/><button className="mt-2 rounded-xl bg-[var(--color-primary)] px-4 py-2 text-xs font-semibold text-white">Add note</button></section></div>}
function Facts({rows}){return <dl className="mt-4 divide-y divide-[var(--color-border)]">{rows.map(([k,v])=><div key={k} className="flex justify-between gap-4 py-3 text-xs"><dt className="text-[var(--color-text-muted)]">{k}</dt><dd className="text-right font-medium">{v||"—"}</dd></div>)}</dl>}
