module.exports = {
  clinicName: "Nova Demo Aesthetic Clinic",
  assistantName: "Avery",
  location: "Kuala Lumpur, Malaysia",
  introMessage: "Hi, I'm Avery from Nova Demo Aesthetic Clinic! 😊",
  consultation: "Complimentary consultation with our clinic team",
  hours: "Monday to Saturday, 10:00 AM to 7:00 PM",
  branches: [
    {
      name: "Kuala Lumpur",
      address: "Bukit Bintang, Kuala Lumpur",
    },
    {
      name: "Petaling Jaya",
      address: "Petaling Jaya, Selangor",
    },
  ],
  services: [
    {
      name: "HIFU Skin Lifting",
      aliases: [
        "hifu",
        "face lifting",
        "v shape",
        "double chin",
        "ultrasound lifting",
        "超声刀",
        "超聲刀",
        "音波拉提",
      ],
      price: "From RM 888",
      duration: "45 to 75 minutes",
      description: "Non-surgical ultrasound treatment commonly used for lifting, tightening and jawline definition.",
    },
    {
      name: "Pico Laser",
      aliases: [
        "pico",
        "pigmentation",
        "dark spots",
        "acne marks",
        "jeragat",
        "bintik hitam",
        "parut jerawat",
        "皮秒",
        "皮秒激光",
        "皮秒雷射",
      ],
      price: "From RM 388",
      duration: "20 to 40 minutes",
      description: "Laser treatment commonly used for pigmentation, uneven tone and selected acne marks.",
    },
    {
      name: "Botulinum Toxin",
      aliases: [
        "botox",
        "jaw slimming",
        "wrinkles",
        "botulinum",
        "肉毒",
        "肉毒杆菌",
        "肉毒桿菌",
        "瘦脸针",
        "瘦臉針",
      ],
      price: "Quoted after consultation because the amount depends on the treatment area",
      duration: "15 to 30 minutes",
      description: "Injection treatment used for selected expression lines and muscle-related facial concerns.",
    },
    {
      name: "Skin Booster",
      aliases: [
        "skin booster",
        "skinbooster",
        "hydration",
        "glow",
        "rejuran",
        "profhilo",
        "水光针",
        "水光針",
        "丽珠兰",
        "麗珠蘭",
      ],
      price: "From RM 688",
      duration: "30 to 45 minutes",
      description: "Injectable treatment category intended to improve hydration, texture and overall skin quality.",
    },
  ],
  faqs: [
    {
      q: "Is consultation free?",
      a: "Yes. This sample clinic offers a complimentary consultation so the team can understand your goals before recommending a treatment.",
    },
    {
      q: "Can I walk in?",
      a: "Appointments are recommended, especially on weekends, so the team can reserve enough consultation time for you.",
    },
    {
      q: "Is it painful?",
      a: "Comfort depends on the treatment and individual sensitivity. The clinic team will explain what to expect and what comfort measures are available before treatment.",
    },
  ],
  promotion: {
    title: "HIFU Demo Special",
    description: "HIFU from RM 888 with a complimentary consultation.",
    assetPath: "/promo-hifu.svg",
  },
};
